parameters:
    open_orchestra_media_admin.navigation_panel.folder.class: OpenOrchestra\MediaAdminBundle\NavigationPanel\Strategies\TreeFolderPanelStrategy

services:
    open_orchestra_media_admin.navigation_panel.folder:
        class: '%open_orchestra_media_admin.navigation_panel.folder.class%'
        arguments:
            - '@open_orchestra_media.repository.media_folder'
            - '@open_orchestra_backoffice.context_manager'
            - '%open_orchestra_backoffice.navigation_panel.menu.editorial%'
            - 245
        tags:
            - { name: open_orchestra_backoffice.navigation_panel.strategy }
